// Run after npm run build: node scripts/tests/settings-ui.cjs
const { join, resolve } = require('node:path')
const { mkdirSync, writeFileSync } = require('node:fs')
if (!process.versions.electron) {
  const { spawnSync } = require('node:child_process')
  const env = { ...process.env }
  delete env.ELECTRON_RUN_AS_NODE
  const result = spawnSync(require('electron'), [__filename], { env, stdio: 'inherit', windowsHide: true })
  process.exit(result.status ?? 1)
}
const { app, BrowserWindow } = require('electron')
const assert = require('node:assert/strict')
const output = resolve(__dirname, '../../.build/settings-smoke')
mkdirSync(output, { recursive: true })
app.setPath('userData', join(output, 'profile'))
app.disableHardwareAcceleration()
const errors = []
let win
const evaluate = (code) => win.webContents.executeJavaScript(code)
const waitFor = async (condition) => {
  const deadline = Date.now() + 10_000
  while (Date.now() < deadline) {
    if (await evaluate(condition)) return
    await new Promise((done) => setTimeout(done, 50))
  }
  throw new Error(`Timed out: ${condition}`)
}
const click = async (selector) => {
  await waitFor(`!!document.querySelector(${JSON.stringify(selector)})`)
  await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`)
}
const clickText = async (selector, text) => {
  const expr = `[...document.querySelectorAll(${JSON.stringify(selector)})].find(el => el.textContent.trim() === ${JSON.stringify(text)})`
  await waitFor(`!!(${expr})`)
  await evaluate(`(${expr}).click()`)
}
const screenshot = async (name) => {
  await evaluate('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))')
  await new Promise((done) => setTimeout(done, 200))
  writeFileSync(join(output, `${name}.png`), (await win.webContents.capturePage()).toPNG())
}
app.whenReady().then(async () => {
  win = new BrowserWindow({ width: 1440, height: 1000, show: false,
    webPreferences: { preload: join(__dirname, 'settings-preload.cjs'), contextIsolation: false, sandbox: false, backgroundThrottling: false, offscreen: true } })
  win.webContents.on('console-message', (_event, level, message) => {
    if (level >= 3) errors.push(message)
  })
  await win.webContents.session.clearStorageData()
  await win.loadFile(resolve(__dirname, '../../out/renderer/index.html'))
  await waitFor(`!!document.querySelector('[title="Настройки языка и внешнего вида"]')`)
  await evaluate(`localStorage.removeItem('settings-smoke')`)
  await click('[title="Настройки языка и внешнего вида"]')
  await waitFor(`!!document.querySelector('.settings-theme-options')`)
  assert.equal(await evaluate(`document.querySelectorAll('.modal-backdrop').length`), 0)
  assert.equal(await evaluate(`!!document.querySelector('.rail-settings[title="Инструменты разработчика"]')`), false)
  await screenshot('appearance-dark')
  await clickText('.settings-nav nav > button', 'Провайдеры агентов')
  await clickText('.settings-provider-nav button', 'Codex')
  await waitFor(`document.querySelector('.settings-content').textContent.includes('68%')`)
  assert.equal(await evaluate(`window.ascora.llm.config().then(c => c.provider)`), 'lmstudio', 'Opening provider settings must not select it in chat')
  await screenshot('codex')
  await click('.settings-toggle-row input')
  await clickText('.settings-nav nav > button', 'Лимиты')
  await waitFor(`!!document.querySelector('.settings-limit-card[data-provider="codex"] progress')`)
  assert.deepEqual(await evaluate(`[...document.querySelectorAll('.settings-nav nav > button')].map(el => el.textContent.trim())`), ['Язык и внешний вид', 'Провайдеры агентов', 'Лимиты', 'Инструменты разработчика'])
  assert.deepEqual(await evaluate(`[...document.querySelectorAll('.settings-limit-card')].map(el => el.dataset.provider)`), ['codex', 'claude', 'grok', 'glm', 'antigravity'], 'Include hidden authorized providers, exclude missing and signed-out CLIs')
  assert.equal(await evaluate(`document.querySelector('.settings-limit-card[data-provider="codex"] progress').value`), 68)
  assert.equal(await evaluate(`document.querySelector('.settings-limit-card[data-provider="codex"] .usage-item time').dateTime`), '2026-09-19T18:00:00Z')
  assert.equal(await evaluate(`!!document.querySelector('.settings-limit-updated time')`), true)
  assert.equal(await evaluate(`document.querySelector('.settings-limit-card[data-provider="grok"]').textContent.includes('пока не поддерживается')`), true)
  assert.equal(await evaluate(`document.querySelector('.settings-limit-card[data-provider="antigravity"] progress').value`), 68)
  await screenshot('limits-dark')
  await evaluate(`Object.assign(window.settingsFixture, { percent: 87, usageFailures: ['claude'], checkFailures: ['grok'] })`)
  await clickText('.settings-content-header button', 'Обновить всё')
  await waitFor(`document.querySelector('.settings-limit-card[data-provider="codex"] progress')?.value === 13`)
  assert.equal(await evaluate(`document.querySelector('.settings-limit-card[data-provider="claude"]').textContent.includes('Usage temporarily unavailable')`), true, 'One failed provider must not block other quotas')
  assert.equal(await evaluate(`document.querySelector('.settings-content').textContent.includes('CLI probe unavailable')`), true)
  await evaluate(`Object.assign(window.settingsFixture, { signedOut: ['codex','claude','copilot','gemini','grok','glm','antigravity'], usageFailures: [], checkFailures: [], percent: 32 })`)
  await clickText('.settings-content-header button', 'Обновить всё')
  await waitFor(`document.querySelector('.settings-content').textContent.includes('Нет авторизованных CLI')`)
  assert.equal(await evaluate(`document.querySelectorAll('.settings-limit-card').length`), 0, 'Logout must clear previously displayed quotas')
  await evaluate(`window.settingsFixture.signedOut = ['copilot']`)
  await clickText('.settings-nav nav > button', 'Провайдеры агентов')
  await click('.settings-toggle-row input')
  for (const name of ['GitHub Copilot', 'Claude', 'Grok CLI', 'GLM (ZCode)', 'Antigravity']) {
    await clickText('.settings-provider-nav button', name)
    await waitFor(`document.querySelector('.settings-content h1')?.textContent === ${JSON.stringify(name)}`)
  }
  await clickText('.settings-provider-nav button', 'Gemini CLI')
  await clickText('.settings-install button', 'Установить автоматически')
  await waitFor(`document.querySelector('.settings-status-grid').textContent.includes('Установлено')`)
  await clickText('.settings-provider-nav button', 'OpenRouter')
  await click('.settings-toggle-row input')
  assert.equal(await evaluate(`window.ascora.settings.get('providers.visibility').then(v => v.openrouter)`), false)
  await click('.settings-back')
  await click('.provider-select-button')
  assert.equal(await evaluate(`[...document.querySelectorAll('.provider-dropdown-option')].some(el => el.textContent.includes('OpenRouter'))`), false)
  win.webContents.reload()
  await waitFor(`!!document.querySelector('[title="Настройки языка и внешнего вида"]')`)
  await click('.provider-select-button')
  assert.equal(await evaluate(`[...document.querySelectorAll('.provider-dropdown-option')].some(el => el.textContent.includes('OpenRouter'))`), false, 'Visibility must survive a reload')
  await click('[title="Настройки языка и внешнего вида"]')
  await clickText('.settings-nav nav > button', 'Провайдеры агентов')
  await clickText('.settings-provider-nav button', 'OpenRouter')
  await click('.settings-toggle-row input')
  await click('.settings-back')
  await click('.provider-select-button')
  await clickText('.provider-dropdown-option', 'OpenRouter')
  await waitFor(`document.querySelector('.settings-content h1')?.textContent === 'OpenRouter'`)
  await clickText('.settings-nav nav > button', 'Инструменты разработчика')
  await waitFor(`!!document.querySelector('.tool-card')`)
  assert.equal(await evaluate(`document.querySelectorAll('.modal-backdrop').length`), 0)
  await screenshot('tools')
  await clickText('.settings-nav nav > button', 'Язык и внешний вид')
  await clickText('.settings-theme', 'Светлая')
  await waitFor(`document.documentElement.dataset.theme === 'light'`)
  await screenshot('appearance-light')
  win.setSize(1000, 800)
  await screenshot('appearance-compact')
  assert.equal(await evaluate(`document.querySelector('.settings-content').scrollWidth > document.querySelector('.settings-content').clientWidth`), false, 'Settings must not overflow horizontally')
  await clickText('.settings-nav nav > button', 'Лимиты')
  await waitFor(`!!document.querySelector('.settings-limit-card progress')`)
  await screenshot('limits-light-compact')
  assert.equal(await evaluate(`document.querySelector('.settings-content').scrollWidth > document.querySelector('.settings-content').clientWidth`), false, 'Limits must not overflow horizontally')
  await click('.settings-back')
  await click('.ws-item')
  await click('.provider-select-button')
  await clickText('.provider-dropdown-option', 'Antigravity (Google)')
  await waitFor(`!!document.querySelector('.composer-select.antigravity-reasoning-select')`)
  assert.deepEqual(await evaluate(`[...document.querySelectorAll('.composer-select.antigravity-reasoning-select option')].map(el => el.textContent)`), ['Low', 'Medium', 'High'])
  await evaluate(`{ const select = document.querySelector('.composer-select.antigravity-reasoning-select'); select.value = 'low'; select.dispatchEvent(new Event('change', { bubbles: true })); }`)
  await waitFor(`document.querySelector('.composer-select.antigravity-reasoning-select').value === 'low'`)
  assert.equal(await evaluate(`window.ascora.llm.config().then(c => c.antigravityReasoning)`), 'low')
  assert.equal(await evaluate(`window.ascora.settings.get('workspace.llm').then(c => c['settings-test'].antigravityReasoning)`), 'low')
  await evaluate(`{ const select = document.querySelector('[title="Antigravity model"]'); select.value = 'pro'; select.dispatchEvent(new Event('change', { bubbles: true })); }`)
  await waitFor(`document.querySelectorAll('.composer-select.antigravity-reasoning-select option').length === 2`)
  assert.deepEqual(await evaluate(`[...document.querySelectorAll('.composer-select.antigravity-reasoning-select option')].map(el => el.textContent)`), ['Low', 'High'], 'Pro must only offer available reasoning variants')
  await evaluate(`{ const select = document.querySelector('[title="Antigravity model"]'); select.value = 'claude_sonnet'; select.dispatchEvent(new Event('change', { bubbles: true })); }`)
  await waitFor(`!document.querySelector('.composer-select.antigravity-reasoning-select')`)
  await evaluate(`{ const select = document.querySelector('[title="Antigravity model"]'); select.value = 'flash'; select.dispatchEvent(new Event('change', { bubbles: true })); }`)
  await waitFor(`document.querySelector('.composer-select.antigravity-reasoning-select')?.value === 'low'`)
  await evaluate(`{
    const input = document.querySelector('.composer-input');
    Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value').set.call(input, 'Тест ты тут?');
    input.dispatchEvent(new Event('input', { bubbles: true }));
  }`)
  await waitFor(`document.querySelector('.send-btn')?.disabled === false`)
  await click('.send-btn')
  await waitFor(`typeof window.settingsFixture.emit === 'function'`)
  assert.equal(await evaluate(`window.settingsFixture.runParams.reasoning`), 'low')
  await evaluate(`window.settingsFixture.emit({ kind: 'item', phase: 'started', item: { id: 'thought', type: 'reasoning', text: 'Preparing a friendly answer.' } })`)
  await waitFor(`!!document.querySelector('.reasoning-block')`)
  await evaluate(`window.settingsFixture.emit({ kind: 'item', phase: 'started', item: { id: 'answer', type: 'agent_message', text: 'Да, я здесь' } })`)
  await waitFor(`document.querySelector('.msg.assistant .bubble')?.textContent.includes('Да, я здесь')`)
  await evaluate(`window.settingsFixture.emit({ kind: 'item', phase: 'started', item: { id: 'answer', type: 'agent_message', text: 'Да, я здесь! Чем могу помочь?' } })`)
  await waitFor(`document.querySelector('.msg.assistant .bubble')?.textContent.includes('Чем могу помочь?')`)
  await evaluate(`window.settingsFixture.emit({ kind: 'item', phase: 'completed', item: { id: 'answer', type: 'agent_message', text: 'Да, я здесь! Чем могу помочь?' } }); window.settingsFixture.finish()`)
  await waitFor(`document.querySelector('.send-btn')?.disabled === true`)
  assert.equal(await evaluate(`document.querySelectorAll('.msg.assistant .bubble').length`), 1, 'Streaming and final events must update a single answer bubble')
  await screenshot('antigravity-answer')

  // Unconfigured Unsloth opens its own settings without changing the chat backend.
  await click('.provider-select-button')
  await clickText('.provider-dropdown-option', 'Unsloth')
  await waitFor(`!!document.querySelector('.unsloth-settings')`)
  assert.equal(await evaluate(`window.ascora.llm.config().then(c => c.provider)`), 'antigravity')
  assert.equal(await evaluate(`document.querySelector('.unsloth-settings input[type="password"]').value`), '')
  const fill = async (selector, value) => {
    await evaluate(`{ const el = document.querySelector(${JSON.stringify(selector)}); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(el, ${JSON.stringify(value)}); el.dispatchEvent(new Event('input', { bubbles: true })); }`)
  }
  await fill('.unsloth-settings input[type="url"]', 'http://127.0.0.1:8888/')
  await fill('.unsloth-settings input[type="password"]', 'invalid')
  await clickText('.unsloth-settings button', 'Сохранить и проверить')
  await waitFor(`document.querySelector('.unsloth-settings .conn-line').textContent.includes('rejected')`)
  await fill('.unsloth-settings input[type="password"]', 'Bearer sk-unsloth-ui-fixture')
  await clickText('.unsloth-settings button', 'Сохранить и проверить')
  await waitFor(`document.querySelectorAll('.unsloth-settings select option').length === 2`)
  assert.equal(await evaluate(`window.ascora.llm.config().then(c => c.unslothBaseUrl)`), 'http://127.0.0.1:8888/v1')
  assert.equal(await evaluate(`window.ascora.llm.config().then(c => c.unslothApiKey)`), 'sk-unsloth-ui-fixture')
  assert.equal(await evaluate(`window.ascora.llm.config().then(c => c.provider)`), 'antigravity')
  assert.equal(await evaluate(`document.querySelector('.unsloth-settings').textContent.includes('sk-unsloth-ui-fixture')`), false)
  await evaluate(`document.querySelector('.unsloth-settings').closest('.settings-card').scrollIntoView({ block: 'start' })`)
  assert.equal(await evaluate(`document.querySelector('.settings-content').scrollWidth > document.querySelector('.settings-content').clientWidth`), false, 'Unsloth form must fit a compact window')
  await screenshot('unsloth-settings')
  await evaluate(`{ const select = document.querySelector('.unsloth-settings select'); select.value = 'unsloth-fixture/model-b'; select.dispatchEvent(new Event('change', { bubbles: true })); }`)
  await clickText('.settings-content-header button', 'Использовать в чате')
  await waitFor(`window.ascora.llm.config().then(c => c.provider === 'unsloth')`)
  await click('.settings-back')
  await waitFor(`document.querySelector('[title="Unsloth model"]')?.value === 'unsloth-fixture/model-b'`)
  assert.equal(await evaluate(`document.querySelector('.statusbar').textContent.includes('Unsloth:')`), true)
  assert.equal(await evaluate(`window.ascora.settings.get('workspace.llm').then(c => c['settings-test'].unslothModel)`), 'unsloth-fixture/model-b')
  assert.equal(await evaluate(`window.ascora.settings.get('workspace.llm').then(c => JSON.stringify(c).includes('sk-unsloth'))`), false)
  win.webContents.reload()
  await waitFor(`document.querySelector('[title="Unsloth model"]')?.value === 'unsloth-fixture/model-b'`)
  assert.equal(await evaluate(`window.ascora.llm.config().then(c => c.unslothApiKey)`), 'sk-unsloth-ui-fixture', 'Connection settings must survive restart')
  await evaluate(`{ const input = document.querySelector('.composer-input'); Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value').set.call(input, 'Unsloth test'); input.dispatchEvent(new Event('input', { bubbles: true })); }`)
  await waitFor(`document.querySelector('.send-btn')?.disabled === false`)
  await click('.send-btn')
  await waitFor(`typeof window.settingsFixture.chatDelta === 'function'`)
  assert.equal(await evaluate(`window.settingsFixture.chatParams.model`), 'unsloth-fixture/model-b')
  assert.ok(await evaluate(`window.settingsFixture.chatParams.tools.length > 0`))
  await evaluate(`window.settingsFixture.chatDelta('Unsloth connection OK.'); window.settingsFixture.chatFinish({ ok: true, content: 'Unsloth connection OK.', toolCalls: [], finishReason: 'stop', usage: { inputTokens: 19, outputTokens: 7 } })`)
  await waitFor(`document.querySelector('.msg.assistant .bubble')?.textContent.includes('Unsloth connection OK.')`)
  await waitFor(`window.settingsFixture.analytics.length > 0`)
  assert.equal(await evaluate(`window.settingsFixture.analytics.at(-1).provider`), 'unsloth')
  assert.equal(await evaluate(`window.settingsFixture.analytics.at(-1).model`), 'unsloth-fixture/model-b')
  await screenshot('unsloth-answer')
  await evaluate(`window.settingsFixture.chatDelta = null; const input = document.querySelector('.composer-input'); Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value').set.call(input, 'Stop test'); input.dispatchEvent(new Event('input', { bubbles: true }));`)
  await click('.send-btn')
  await waitFor(`typeof window.settingsFixture.chatDelta === 'function'`)
  await click('.send-btn')
  await waitFor(`!!window.settingsFixture.abortId`)
  assert.equal(await evaluate(`window.settingsFixture.abortId`), await evaluate(`window.settingsFixture.chatId`), 'Stop must abort the actual HTTP request')
  await click('[title="Настройки языка и внешнего вида"]')
  await clickText('.settings-nav nav > button', 'Провайдеры агентов')
  await clickText('.settings-provider-nav button', 'Unsloth')
  await evaluate(`window.settingsFixture.unslothModels = []`)
  await clickText('.unsloth-settings button', 'Обновить модели')
  await waitFor(`document.querySelector('.unsloth-settings select')?.disabled === true`)
  assert.equal(await evaluate(`window.ascora.llm.config().then(c => c.unslothModel)`), '')
  await click('.settings-toggle-row input')
  await click('.settings-back')
  await click('.provider-select-button')
  assert.equal(await evaluate(`[...document.querySelectorAll('.provider-dropdown-option')].some(el => el.textContent === 'Unsloth')`), false)
  assert.equal(await evaluate(`window.ascora.settings.get('providers.visibility').then(v => v.unsloth)`), false)
  assert.deepEqual(errors, [])
  console.log('Settings UI OK: navigation, quotas, installation, visibility, themes, Antigravity reasoning/answers; Unsloth setup, invalid key, models, persistence, streaming, analytics and cancellation')
  app.exit(0)
}).catch((error) => { console.error(error, errors); app.exit(1) })
